packages:
    github.com/tuantran1810/go-di-template/internal/usecases:
        config:
            dir: "mocks/usecases"
            filename: "mock_{{.InterfaceName}}.go"
        interfaces:
            IUserRepository:
                config:
            IUserAttributeRepository:
                config:
            IUUIDGenerator:
                config:
            IMessageRepository:
                config:
            IClient:
                config:
    github.com/tuantran1810/go-di-template/internal/controllers:
        config:
            dir: "mocks/controllers"
            filename: "mock_{{.InterfaceName}}.go"
        interfaces:
            IUserUsecase:
                config:
            ILoggingWorker:
                config:
