// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecases

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuantran1810/go-di-template/internal/entities"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Create(ctx context.Context, tx entities.Transaction, user *entities.User) (*entities.User, error) {
	ret := _mock.Called(ctx, tx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Transaction, *entities.User) (*entities.User, error)); ok {
		return returnFunc(ctx, tx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Transaction, *entities.User) *entities.User); ok {
		r0 = returnFunc(ctx, tx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Transaction, *entities.User) error); ok {
		r1 = returnFunc(ctx, tx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - tx
//   - user
func (_e *MockIUserRepository_Expecter) Create(ctx interface{}, tx interface{}, user interface{}) *MockIUserRepository_Create_Call {
	return &MockIUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, user)}
}

func (_c *MockIUserRepository_Create_Call) Run(run func(ctx context.Context, tx entities.Transaction, user *entities.User)) *MockIUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Transaction), args[2].(*entities.User))
	})
	return _c
}

func (_c *MockIUserRepository_Create_Call) Return(user1 *entities.User, err error) *MockIUserRepository_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx entities.Transaction, user *entities.User) (*entities.User, error)) *MockIUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FindByUsername(ctx context.Context, tx entities.Transaction, username string) (*entities.User, error) {
	ret := _mock.Called(ctx, tx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Transaction, string) (*entities.User, error)); ok {
		return returnFunc(ctx, tx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Transaction, string) *entities.User); ok {
		r0 = returnFunc(ctx, tx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Transaction, string) error); ok {
		r1 = returnFunc(ctx, tx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockIUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx
//   - tx
//   - username
func (_e *MockIUserRepository_Expecter) FindByUsername(ctx interface{}, tx interface{}, username interface{}) *MockIUserRepository_FindByUsername_Call {
	return &MockIUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, tx, username)}
}

func (_c *MockIUserRepository_FindByUsername_Call) Run(run func(ctx context.Context, tx entities.Transaction, username string)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Transaction), args[2].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) Return(user *entities.User, err error) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, tx entities.Transaction, username string) (*entities.User, error)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// RunTx provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) RunTx(ctx context.Context, funcs ...entities.DBTxHandleFunc) error {
	var tmpRet mock.Arguments
	if len(funcs) > 0 {
		tmpRet = _mock.Called(ctx, funcs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...entities.DBTxHandleFunc) error); ok {
		r0 = returnFunc(ctx, funcs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_RunTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTx'
type MockIUserRepository_RunTx_Call struct {
	*mock.Call
}

// RunTx is a helper method to define mock.On call
//   - ctx
//   - funcs
func (_e *MockIUserRepository_Expecter) RunTx(ctx interface{}, funcs ...interface{}) *MockIUserRepository_RunTx_Call {
	return &MockIUserRepository_RunTx_Call{Call: _e.mock.On("RunTx",
		append([]interface{}{ctx}, funcs...)...)}
}

func (_c *MockIUserRepository_RunTx_Call) Run(run func(ctx context.Context, funcs ...entities.DBTxHandleFunc)) *MockIUserRepository_RunTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]entities.DBTxHandleFunc)
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockIUserRepository_RunTx_Call) Return(err error) *MockIUserRepository_RunTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_RunTx_Call) RunAndReturn(run func(ctx context.Context, funcs ...entities.DBTxHandleFunc) error) *MockIUserRepository_RunTx_Call {
	_c.Call.Return(run)
	return _c
}
