// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecases

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUUIDGenerator creates a new instance of MockIUUIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUUIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUUIDGenerator {
	mock := &MockIUUIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUUIDGenerator is an autogenerated mock type for the IUUIDGenerator type
type MockIUUIDGenerator struct {
	mock.Mock
}

type MockIUUIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUUIDGenerator) EXPECT() *MockIUUIDGenerator_Expecter {
	return &MockIUUIDGenerator_Expecter{mock: &_m.Mock}
}

// MustNewUUID provides a mock function for the type MockIUUIDGenerator
func (_mock *MockIUUIDGenerator) MustNewUUID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MustNewUUID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIUUIDGenerator_MustNewUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustNewUUID'
type MockIUUIDGenerator_MustNewUUID_Call struct {
	*mock.Call
}

// MustNewUUID is a helper method to define mock.On call
func (_e *MockIUUIDGenerator_Expecter) MustNewUUID() *MockIUUIDGenerator_MustNewUUID_Call {
	return &MockIUUIDGenerator_MustNewUUID_Call{Call: _e.mock.On("MustNewUUID")}
}

func (_c *MockIUUIDGenerator_MustNewUUID_Call) Run(run func()) *MockIUUIDGenerator_MustNewUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUUIDGenerator_MustNewUUID_Call) Return(s string) *MockIUUIDGenerator_MustNewUUID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIUUIDGenerator_MustNewUUID_Call) RunAndReturn(run func() string) *MockIUUIDGenerator_MustNewUUID_Call {
	_c.Call.Return(run)
	return _c
}
